name: Build and Release NixOS limine boot ISO

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Nix Cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock', '**/flake.nix') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-

      - name: Build ISO Image
        run: |
          nix build .#minimalISO --print-build-logs

      - name: Upload ISO to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ inputs.tag_name }}
          tag_name: ${{ inputs.tag_name }}
          files: 'result/nixos-limine.iso'
          draft: false
          prerelease: false
          
      - name: Prepare ISO Asset
        id: prepare
        run: |
          cp -L result/nixos-limine.iso ./nixos-limine.iso

      - name: Upload ISO to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: Release ${{ inputs.tag_name }}
          files: nixos-limine.iso
          draft: false
          prerelease: false